namespace RecipeShare.Util.Helpers.Enums
{
	public enum DietaryTagEnums
	{
		None = 0,
		Vegetarian = 1,
		Vegan = 2,
		Pescatarian = 3,
		GlutenFree = 4,
		DairyFree = 5,
		NutFree = 6,
		Halal = 7,
		Kosher = 8,
		LowCarb = 9,
		LowFat = 10,
		HighProtein = 11,
		LowSodium = 12,
		LowSugar = 13,
		Organic = 14,
		NonGMO = 15,
		Whole30 = 16,
		Paleo = 17,
		Keto = 18,
		FODMAPFriendly = 19,
		DiabeticFriendly = 20,
		HeartHealthy = 21,
		AntiInflammatory = 22,
		Raw = 23,
		LowCholesterol = 24,
		HighFiber = 25,
		LowCalorie = 26,
		IntermittentFasting = 27,
		AllergenFriendly = 28,
		SugarFree = 29,
		LowHistamine = 30,
		LowOxalate = 31,
		LowFODMAP = 32,
		LowPurine = 33,
		LowPhosphorus = 34,
		LowPotassium = 35,
		LowMagnesium = 36,
		LowCalcium = 37,
		LowIron = 38,
		LowZinc = 39,
		LowCopper = 40,
		LowSelenium = 41,
		LowManganese = 42,
		LowIodine = 43,
		LowFluoride = 44,
		LowChloride = 45,
	}
}